version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    build:
     context: ./
     dockerfile: php/Dockerfile
    volumes:
     - ./www/html:/var/www/html

  mail:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
